<?php
namespace Abianbiya\Laralag\Seeders;
use Illuminate\Database\Seeder;

class ConfigPermissionTableSeeder extends Seeder
{
    public function run()
    {
        \DB::table('permission')->insert(array(
            // config-group permissions (7 standard CRUD)
            0 => array(
                'id' => 'b0000001-0000-4000-8000-000000000001',
                'slug' => 'config-group.index',
                'nama' => 'Melihat daftar Config Group',
                'action' => 'index',
                'group' => 'config-group',
                'description' => NULL,
                'created_at' => '2026-03-13 00:00:00',
                'updated_at' => '2026-03-13 00:00:00',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            1 => array(
                'id' => 'b0000001-0000-4000-8000-000000000002',
                'slug' => 'config-group.create',
                'nama' => 'Menampilkan form tambah Config Group',
                'action' => 'create',
                'group' => 'config-group',
                'description' => NULL,
                'created_at' => '2026-03-13 00:00:00',
                'updated_at' => '2026-03-13 00:00:00',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            2 => array(
                'id' => 'b0000001-0000-4000-8000-000000000003',
                'slug' => 'config-group.store',
                'nama' => 'Menyimpan Config Group baru',
                'action' => 'store',
                'group' => 'config-group',
                'description' => NULL,
                'created_at' => '2026-03-13 00:00:00',
                'updated_at' => '2026-03-13 00:00:00',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            3 => array(
                'id' => 'b0000001-0000-4000-8000-000000000004',
                'slug' => 'config-group.show',
                'nama' => 'Melihat detail Config Group',
                'action' => 'show',
                'group' => 'config-group',
                'description' => NULL,
                'created_at' => '2026-03-13 00:00:00',
                'updated_at' => '2026-03-13 00:00:00',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            4 => array(
                'id' => 'b0000001-0000-4000-8000-000000000005',
                'slug' => 'config-group.edit',
                'nama' => 'Menampilkan form edit Config Group',
                'action' => 'edit',
                'group' => 'config-group',
                'description' => NULL,
                'created_at' => '2026-03-13 00:00:00',
                'updated_at' => '2026-03-13 00:00:00',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            5 => array(
                'id' => 'b0000001-0000-4000-8000-000000000006',
                'slug' => 'config-group.update',
                'nama' => 'Mengubah Config Group',
                'action' => 'update',
                'group' => 'config-group',
                'description' => NULL,
                'created_at' => '2026-03-13 00:00:00',
                'updated_at' => '2026-03-13 00:00:00',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            6 => array(
                'id' => 'b0000001-0000-4000-8000-000000000007',
                'slug' => 'config-group.destroy',
                'nama' => 'Menghapus Config Group',
                'action' => 'destroy',
                'group' => 'config-group',
                'description' => NULL,
                'created_at' => '2026-03-13 00:00:00',
                'updated_at' => '2026-03-13 00:00:00',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            // config permission
            7 => array(
                'id' => 'b0000001-0000-4000-8000-000000000008',
                'slug' => 'config.index',
                'nama' => 'Melihat halaman Pengaturan',
                'action' => 'index',
                'group' => 'config',
                'description' => NULL,
                'created_at' => '2026-03-13 00:00:00',
                'updated_at' => '2026-03-13 00:00:00',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            // config-general permissions
            8 => array(
                'id' => 'b0000001-0000-4000-8000-000000000009',
                'slug' => 'config-general.index',
                'nama' => 'Melihat pengaturan Pengaturan Umum',
                'action' => 'index',
                'group' => 'config-general',
                'description' => NULL,
                'created_at' => '2026-03-13 00:00:00',
                'updated_at' => '2026-03-13 00:00:00',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            9 => array(
                'id' => 'b0000001-0000-4000-8000-000000000010',
                'slug' => 'config-general.update',
                'nama' => 'Mengubah pengaturan Pengaturan Umum',
                'action' => 'update',
                'group' => 'config-general',
                'description' => NULL,
                'created_at' => '2026-03-13 00:00:00',
                'updated_at' => '2026-03-13 00:00:00',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            // config-display permissions
            10 => array(
                'id' => 'b0000001-0000-4000-8000-000000000011',
                'slug' => 'config-display.index',
                'nama' => 'Melihat pengaturan Tampilan',
                'action' => 'index',
                'group' => 'config-display',
                'description' => NULL,
                'created_at' => '2026-03-13 00:00:00',
                'updated_at' => '2026-03-13 00:00:00',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            11 => array(
                'id' => 'b0000001-0000-4000-8000-000000000012',
                'slug' => 'config-display.update',
                'nama' => 'Mengubah pengaturan Tampilan',
                'action' => 'update',
                'group' => 'config-display',
                'description' => NULL,
                'created_at' => '2026-03-13 00:00:00',
                'updated_at' => '2026-03-13 00:00:00',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            // config-auth permissions
            12 => array(
                'id' => 'b0000001-0000-4000-8000-000000000013',
                'slug' => 'config-auth.index',
                'nama' => 'Melihat pengaturan Autentikasi',
                'action' => 'index',
                'group' => 'config-auth',
                'description' => NULL,
                'created_at' => '2026-03-13 00:00:00',
                'updated_at' => '2026-03-13 00:00:00',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            13 => array(
                'id' => 'b0000001-0000-4000-8000-000000000014',
                'slug' => 'config-auth.update',
                'nama' => 'Mengubah pengaturan Autentikasi',
                'action' => 'update',
                'group' => 'config-auth',
                'description' => NULL,
                'created_at' => '2026-03-13 00:00:00',
                'updated_at' => '2026-03-13 00:00:00',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
        ));
    }
}
