<?php
namespace Abianbiya\Laralag\Seeders;
use Illuminate\Database\Seeder;

class ConfigTableSeeder extends Seeder
{
    public function run()
    {
        \DB::table('config')->delete();
        \DB::table('config')->insert(array(
            // General group
            0 => array(
                'id' => 'a0000002-0000-4000-8000-000000000001',
                'config_group_id' => 'a0000001-0000-4000-8000-000000000001',
                'key' => 'general.app_name',
                'config_name' => 'Nama Aplikasi',
                'default_value' => 'Laralag',
                'form_type' => 'text',
                'form_help' => 'Nama yang ditampilkan di header',
                'form_options' => NULL,
                'form_label' => NULL,
                'form_placeholder' => NULL,
                'is_multiple' => 0,
                'is_tampil' => 1,
                'urutan' => 1,
                'validation_rules' => NULL,
                'created_at' => '2026-03-13 00:00:00',
                'updated_at' => '2026-03-13 00:00:00',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            1 => array(
                'id' => 'a0000002-0000-4000-8000-000000000002',
                'config_group_id' => 'a0000001-0000-4000-8000-000000000001',
                'key' => 'general.app_short_name',
                'config_name' => 'Nama Singkat',
                'default_value' => 'LAG',
                'form_type' => 'text',
                'form_help' => 'Nama singkat aplikasi',
                'form_options' => NULL,
                'form_label' => NULL,
                'form_placeholder' => NULL,
                'is_multiple' => 0,
                'is_tampil' => 1,
                'urutan' => 2,
                'validation_rules' => NULL,
                'created_at' => '2026-03-13 00:00:00',
                'updated_at' => '2026-03-13 00:00:00',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            2 => array(
                'id' => 'a0000002-0000-4000-8000-000000000003',
                'config_group_id' => 'a0000001-0000-4000-8000-000000000001',
                'key' => 'general.home_route',
                'config_name' => 'Route Beranda',
                'default_value' => 'dashboard.index',
                'form_type' => 'text',
                'form_help' => 'Route setelah login berhasil',
                'form_options' => NULL,
                'form_label' => NULL,
                'form_placeholder' => NULL,
                'is_multiple' => 0,
                'is_tampil' => 1,
                'urutan' => 3,
                'validation_rules' => NULL,
                'created_at' => '2026-03-13 00:00:00',
                'updated_at' => '2026-03-13 00:00:00',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            3 => array(
                'id' => 'a0000002-0000-4000-8000-000000000004',
                'config_group_id' => 'a0000001-0000-4000-8000-000000000001',
                'key' => 'general.landing_route',
                'config_name' => 'Route Landing',
                'default_value' => 'home.index',
                'form_type' => 'text',
                'form_help' => 'Route halaman landing',
                'form_options' => NULL,
                'form_label' => NULL,
                'form_placeholder' => NULL,
                'is_multiple' => 0,
                'is_tampil' => 1,
                'urutan' => 4,
                'validation_rules' => NULL,
                'created_at' => '2026-03-13 00:00:00',
                'updated_at' => '2026-03-13 00:00:00',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            4 => array(
                'id' => 'a0000002-0000-4000-8000-000000000005',
                'config_group_id' => 'a0000001-0000-4000-8000-000000000001',
                'key' => 'general.has_landing',
                'config_name' => 'Punya Landing Page',
                'default_value' => '0',
                'form_type' => 'toggle',
                'form_help' => 'Aktifkan halaman landing',
                'form_options' => NULL,
                'form_label' => NULL,
                'form_placeholder' => NULL,
                'is_multiple' => 0,
                'is_tampil' => 1,
                'urutan' => 5,
                'validation_rules' => NULL,
                'created_at' => '2026-03-13 00:00:00',
                'updated_at' => '2026-03-13 00:00:00',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            // Display group
            5 => array(
                'id' => 'a0000002-0000-4000-8000-000000000006',
                'config_group_id' => 'a0000001-0000-4000-8000-000000000002',
                'key' => 'display.default_pagination',
                'config_name' => 'Paginasi Default',
                'default_value' => '10',
                'form_type' => 'number',
                'form_help' => 'Jumlah item per halaman',
                'form_options' => NULL,
                'form_label' => NULL,
                'form_placeholder' => NULL,
                'is_multiple' => 0,
                'is_tampil' => 1,
                'urutan' => 1,
                'validation_rules' => NULL,
                'created_at' => '2026-03-13 00:00:00',
                'updated_at' => '2026-03-13 00:00:00',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            6 => array(
                'id' => 'a0000002-0000-4000-8000-000000000007',
                'config_group_id' => 'a0000001-0000-4000-8000-000000000002',
                'key' => 'display.use_bootstrap_pagination',
                'config_name' => 'Bootstrap Pagination',
                'default_value' => '1',
                'form_type' => 'toggle',
                'form_help' => 'Gunakan styling Bootstrap untuk paginasi',
                'form_options' => NULL,
                'form_label' => NULL,
                'form_placeholder' => NULL,
                'is_multiple' => 0,
                'is_tampil' => 1,
                'urutan' => 2,
                'validation_rules' => NULL,
                'created_at' => '2026-03-13 00:00:00',
                'updated_at' => '2026-03-13 00:00:00',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            7 => array(
                'id' => 'a0000002-0000-4000-8000-000000000008',
                'config_group_id' => 'a0000001-0000-4000-8000-000000000002',
                'key' => 'display.theme_customizer_enabled',
                'config_name' => 'Theme Customizer',
                'default_value' => '0',
                'form_type' => 'toggle',
                'form_help' => 'Aktifkan theme customizer',
                'form_options' => NULL,
                'form_label' => NULL,
                'form_placeholder' => NULL,
                'is_multiple' => 0,
                'is_tampil' => 1,
                'urutan' => 3,
                'validation_rules' => NULL,
                'created_at' => '2026-03-13 00:00:00',
                'updated_at' => '2026-03-13 00:00:00',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            8 => array(
                'id' => 'a0000002-0000-4000-8000-000000000009',
                'config_group_id' => 'a0000001-0000-4000-8000-000000000002',
                'key' => 'display.boolean_labels',
                'config_name' => 'Label Boolean',
                'default_value' => '{"1":"Ya","0":"Tidak"}',
                'form_type' => 'textarea',
                'form_help' => 'Format JSON: {"1":"Ya","0":"Tidak"}',
                'form_options' => NULL,
                'form_label' => NULL,
                'form_placeholder' => NULL,
                'is_multiple' => 0,
                'is_tampil' => 1,
                'urutan' => 4,
                'validation_rules' => NULL,
                'created_at' => '2026-03-13 00:00:00',
                'updated_at' => '2026-03-13 00:00:00',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            // Auth group
            9 => array(
                'id' => 'a0000002-0000-4000-8000-000000000010',
                'config_group_id' => 'a0000001-0000-4000-8000-000000000003',
                'key' => 'auth.custom_login_blade',
                'config_name' => 'Custom Login Blade',
                'default_value' => '',
                'form_type' => 'text',
                'form_help' => 'Nama blade custom untuk halaman login (kosong = default)',
                'form_options' => NULL,
                'form_label' => NULL,
                'form_placeholder' => NULL,
                'is_multiple' => 0,
                'is_tampil' => 1,
                'urutan' => 1,
                'validation_rules' => NULL,
                'created_at' => '2026-03-13 00:00:00',
                'updated_at' => '2026-03-13 00:00:00',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            10 => array(
                'id' => 'a0000002-0000-4000-8000-000000000011',
                'config_group_id' => 'a0000001-0000-4000-8000-000000000003',
                'key' => 'auth.custom_register_blade',
                'config_name' => 'Custom Register Blade',
                'default_value' => '',
                'form_type' => 'text',
                'form_help' => 'Nama blade custom untuk halaman register (kosong = default)',
                'form_options' => NULL,
                'form_label' => NULL,
                'form_placeholder' => NULL,
                'is_multiple' => 0,
                'is_tampil' => 1,
                'urutan' => 2,
                'validation_rules' => NULL,
                'created_at' => '2026-03-13 00:00:00',
                'updated_at' => '2026-03-13 00:00:00',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            11 => array(
                'id' => 'a0000002-0000-4000-8000-000000000012',
                'config_group_id' => 'a0000001-0000-4000-8000-000000000003',
                'key' => 'auth.dashboard_blade',
                'config_name' => 'Dashboard Blade',
                'default_value' => '',
                'form_type' => 'text',
                'form_help' => 'Nama blade custom untuk dashboard (kosong = default)',
                'form_options' => NULL,
                'form_label' => NULL,
                'form_placeholder' => NULL,
                'is_multiple' => 0,
                'is_tampil' => 1,
                'urutan' => 3,
                'validation_rules' => NULL,
                'created_at' => '2026-03-13 00:00:00',
                'updated_at' => '2026-03-13 00:00:00',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
        ));
    }
}
