<?php

namespace Abianbiya\Laralag\Seeders;

use Illuminate\Database\Seeder;

class PermissionTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('permission')->delete();

        \DB::table('permission')->insert(array(
            0 =>
            array(
                'id' => '9c143c88-b996-4638-8a44-2696abccfd2a',
                'slug' => 'menu.create',
                'nama' => 'Menampilkan form tambah Menu',
                'action' => 'create',
                'group' => 'menu',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            1 =>
            array(
                'id' => '9c143c88-bc38-4705-93c2-e026392f96f9',
                'slug' => 'menu.destroy',
                'nama' => 'Menghapus Menu',
                'action' => 'destroy',
                'group' => 'menu',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            2 =>
            array(
                'id' => '9c143c88-bca4-406a-a587-f08de3200a5f',
                'slug' => 'menu.edit',
                'nama' => 'Menampilkan form edit Menu',
                'action' => 'edit',
                'group' => 'menu',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            3 =>
            array(
                'id' => '9c143c88-bcfc-4513-b7bc-e0ee069131d7',
                'slug' => 'menu.index',
                'nama' => 'Melihat daftar Menu',
                'action' => 'index',
                'group' => 'menu',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            4 =>
            array(
                'id' => '9c143c88-bd54-40e2-8b34-386e7f0e1aa4',
                'slug' => 'menu.show',
                'nama' => 'Menampilkan detail Menu',
                'action' => 'show',
                'group' => 'menu',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            5 =>
            array(
                'id' => '9c143c88-bdaf-4548-bf26-e64e152fcf20',
                'slug' => 'menu.store',
                'nama' => 'Menyimpan form tambah Menu',
                'action' => 'store',
                'group' => 'menu',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            6 =>
            array(
                'id' => '9c143c88-be19-44fd-a9c7-720abce3da06',
                'slug' => 'menu.update',
                'nama' => 'Menyimpan form edit Menu',
                'action' => 'update',
                'group' => 'menu',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            7 =>
            array(
                'id' => '9c143c88-be66-44f1-993d-5e67a8b0b976',
                'slug' => 'menugroup.create',
                'nama' => 'Menampilkan form tambah Menugroup',
                'action' => 'create',
                'group' => 'menugroup',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            8 =>
            array(
                'id' => '9c143c88-bec4-4788-9a24-41d787f1cc45',
                'slug' => 'menugroup.destroy',
                'nama' => 'Menghapus Menugroup',
                'action' => 'destroy',
                'group' => 'menugroup',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            9 =>
            array(
                'id' => '9c143c88-bf18-4d75-9618-5f124a6a5903',
                'slug' => 'menugroup.edit',
                'nama' => 'Menampilkan form edit Menugroup',
                'action' => 'edit',
                'group' => 'menugroup',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            10 =>
            array(
                'id' => '9c143c88-bf78-45d8-bdbc-9972f51cad3f',
                'slug' => 'menugroup.index',
                'nama' => 'Melihat daftar Menugroup',
                'action' => 'index',
                'group' => 'menugroup',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            11 =>
            array(
                'id' => '9c143c88-bfd6-496b-b680-a61c0e068ad8',
                'slug' => 'menugroup.show',
                'nama' => 'Menampilkan detail Menugroup',
                'action' => 'show',
                'group' => 'menugroup',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            12 =>
            array(
                'id' => '9c143c88-c039-4338-90f8-99dbbf21d7b6',
                'slug' => 'menugroup.store',
                'nama' => 'Menyimpan form tambah Menugroup',
                'action' => 'store',
                'group' => 'menugroup',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            13 =>
            array(
                'id' => '9c143c88-c0b2-4478-94d7-310a808beea7',
                'slug' => 'menugroup.update',
                'nama' => 'Menyimpan form edit Menugroup',
                'action' => 'update',
                'group' => 'menugroup',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            14 =>
            array(
                'id' => '9c143c88-c11d-4716-9268-2e05212e5199',
                'slug' => 'module.create',
                'nama' => 'Menampilkan form tambah Module',
                'action' => 'create',
                'group' => 'module',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            15 =>
            array(
                'id' => '9c143c88-c180-45ef-a8d1-7de0d4c8eb46',
                'slug' => 'module.destroy',
                'nama' => 'Menghapus Module',
                'action' => 'destroy',
                'group' => 'module',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            16 =>
            array(
                'id' => '9c143c88-c1f5-44c5-baf4-c530701657b5',
                'slug' => 'module.edit',
                'nama' => 'Menampilkan form edit Module',
                'action' => 'edit',
                'group' => 'module',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            17 =>
            array(
                'id' => '9c143c88-c2c5-4bc9-bd35-a7913968bd52',
                'slug' => 'module.index',
                'nama' => 'Melihat daftar Module',
                'action' => 'index',
                'group' => 'module',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            18 =>
            array(
                'id' => '9c143c88-c322-47d3-8b90-6ae20730aa02',
                'slug' => 'module.show',
                'nama' => 'Menampilkan detail Module',
                'action' => 'show',
                'group' => 'module',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            19 =>
            array(
                'id' => '9c143c88-c388-4f20-9d74-a327cd2cbaf0',
                'slug' => 'module.store',
                'nama' => 'Menyimpan form tambah Module',
                'action' => 'store',
                'group' => 'module',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            20 =>
            array(
                'id' => '9c143c88-c3fa-4fac-a19e-8e5fa1a92295',
                'slug' => 'module.update',
                'nama' => 'Menyimpan form edit Module',
                'action' => 'update',
                'group' => 'module',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            21 =>
            array(
                'id' => '9c143c88-c461-4192-8594-8f8761a0ac2b',
                'slug' => 'permission.create',
                'nama' => 'Menampilkan form tambah Permission',
                'action' => 'create',
                'group' => 'permission',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            22 =>
            array(
                'id' => '9c143c88-c4c2-4366-a231-887eb37d9f56',
                'slug' => 'permission.destroy',
                'nama' => 'Menghapus Permission',
                'action' => 'destroy',
                'group' => 'permission',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            23 =>
            array(
                'id' => '9c143c88-c53c-4169-9006-3d8e24764851',
                'slug' => 'permission.edit',
                'nama' => 'Menampilkan form edit Permission',
                'action' => 'edit',
                'group' => 'permission',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            24 =>
            array(
                'id' => '9c143c88-c5a0-42a5-aa92-e75111720ffa',
                'slug' => 'permission.index',
                'nama' => 'Melihat daftar Permission',
                'action' => 'index',
                'group' => 'permission',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            25 =>
            array(
                'id' => '9c143c88-c60a-4fcf-98cd-3030d67dd745',
                'slug' => 'permission.show',
                'nama' => 'Menampilkan detail Permission',
                'action' => 'show',
                'group' => 'permission',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            26 =>
            array(
                'id' => '9c143c88-c668-41ae-91fd-7836ce41e978',
                'slug' => 'permission.store',
                'nama' => 'Menyimpan form tambah Permission',
                'action' => 'store',
                'group' => 'permission',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            27 =>
            array(
                'id' => '9c143c88-c6cb-48e9-99ac-e8e44b2e0c04',
                'slug' => 'permission.update',
                'nama' => 'Menyimpan form edit Permission',
                'action' => 'update',
                'group' => 'permission',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            28 =>
            array(
                'id' => '9c143c88-cd0d-455f-a5f2-1bd044f5fe71',
                'slug' => 'role.create',
                'nama' => 'Menampilkan form tambah Role',
                'action' => 'create',
                'group' => 'role',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            29 =>
            array(
                'id' => '9c143c88-cd60-44c7-a1f2-6b22b9dfbe60',
                'slug' => 'role.destroy',
                'nama' => 'Menghapus Role',
                'action' => 'destroy',
                'group' => 'role',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            30 =>
            array(
                'id' => '9c143c88-cdb0-43f0-b45e-a0075e011efe',
                'slug' => 'role.edit',
                'nama' => 'Menampilkan form edit Role',
                'action' => 'edit',
                'group' => 'role',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            31 =>
            array(
                'id' => '9c143c88-ce0d-44c4-bf83-923a5e3ed3d8',
                'slug' => 'role.index',
                'nama' => 'Melihat daftar Role',
                'action' => 'index',
                'group' => 'role',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            32 =>
            array(
                'id' => '9c143c88-ce63-42f9-9e4d-b2412bacde79',
                'slug' => 'role.permission.update',
                'nama' => 'Menyimpan form edit Role Permission ',
                'action' => 'update',
                'group' => 'role',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            33 =>
            array(
                'id' => '9c143c88-ceb7-437c-a417-f7506d1d92bf',
                'slug' => 'role.show',
                'nama' => 'Menampilkan detail Role',
                'action' => 'show',
                'group' => 'role',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            34 =>
            array(
                'id' => '9c143c88-cef9-4582-96b3-f7affd56ec22',
                'slug' => 'role.store',
                'nama' => 'Menyimpan form tambah Role',
                'action' => 'store',
                'group' => 'role',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            35 =>
            array(
                'id' => '9c143c88-cf3b-4bce-8c18-44df5b41e35a',
                'slug' => 'role.update',
                'nama' => 'Menyimpan form edit Role',
                'action' => 'update',
                'group' => 'role',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            36 =>
            array(
                'id' => '9c143c88-d157-4c5c-b2a4-12d6b674a6c2',
                'slug' => 'user.create',
                'nama' => 'Menampilkan form tambah User',
                'action' => 'create',
                'group' => 'user',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            37 =>
            array(
                'id' => '9c143c88-d1ac-4ec9-a099-108654b86be9',
                'slug' => 'user.destroy',
                'nama' => 'Menghapus User',
                'action' => 'destroy',
                'group' => 'user',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            38 =>
            array(
                'id' => '9c143c88-d1fe-4c64-a45c-a0eefc3d65a3',
                'slug' => 'user.edit',
                'nama' => 'Menampilkan form edit User',
                'action' => 'edit',
                'group' => 'user',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            39 =>
            array(
                'id' => '9c143c88-d243-4623-bdf8-c81eba2eab32',
                'slug' => 'user.index',
                'nama' => 'Melihat daftar User',
                'action' => 'index',
                'group' => 'user',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            40 =>
            array(
                'id' => '9c143c88-d280-4222-9f4b-b6760f2849e5',
                'slug' => 'user.show',
                'nama' => 'Menampilkan detail User',
                'action' => 'show',
                'group' => 'user',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            41 =>
            array(
                'id' => '9c143c88-d2bd-4ddd-825d-66ee681985b6',
                'slug' => 'user.store',
                'nama' => 'Menyimpan form tambah User',
                'action' => 'store',
                'group' => 'user',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            42 =>
            array(
                'id' => '9c143c88-d2f9-493b-a346-ce5d252032de',
                'slug' => 'user.update',
                'nama' => 'Menyimpan form edit User',
                'action' => 'update',
                'group' => 'user',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            43 =>
            array(
                'id' => '9c17bd8d-5f23-45e6-8adf-e012ee161ac6',
                'slug' => 'log.create',
                'nama' => 'Menampilkan form tambah Log',
                'action' => 'create',
                'group' => 'log',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            44 =>
            array(
                'id' => '9c17bd8d-630c-403d-a0da-147212e95f0d',
                'slug' => 'log.destroy',
                'nama' => 'Menghapus Log',
                'action' => 'destroy',
                'group' => 'log',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            45 =>
            array(
                'id' => '9c17bd8d-6376-48ab-8357-f61f4ead4088',
                'slug' => 'log.edit',
                'nama' => 'Menampilkan form edit Log',
                'action' => 'edit',
                'group' => 'log',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            46 =>
            array(
                'id' => '9c17bd8d-63d8-41e5-b5c7-177d26ba4594',
                'slug' => 'log.index',
                'nama' => 'Melihat daftar Log',
                'action' => 'index',
                'group' => 'log',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            47 =>
            array(
                'id' => '9c17bd8d-6446-439c-a48f-45507b2eee28',
                'slug' => 'log.show',
                'nama' => 'Menampilkan detail Log',
                'action' => 'show',
                'group' => 'log',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            48 =>
            array(
                'id' => '9c17bd8d-64af-4049-9779-ce94a0e143e7',
                'slug' => 'log.store',
                'nama' => 'Menyimpan form tambah Log',
                'action' => 'store',
                'group' => 'log',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            49 =>
            array(
                'id' => '9c17bd8d-6526-4026-ba72-e32a8c5bc7ed',
                'slug' => 'log.update',
                'nama' => 'Menyimpan form edit Log',
                'action' => 'update',
                'group' => 'log',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            50 =>
            array(
                'id' => '9c17bd8d-6f14-4a97-878b-d71fc5187296',
                'slug' => 'permissionrole.create',
                'nama' => 'Menampilkan form tambah Permissionrole',
                'action' => 'create',
                'group' => 'permissionrole',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            51 =>
            array(
                'id' => '9c17bd8d-6f99-4fc5-9350-0a6858250d2d',
                'slug' => 'permissionrole.destroy',
                'nama' => 'Menghapus Permissionrole',
                'action' => 'destroy',
                'group' => 'permissionrole',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            52 =>
            array(
                'id' => '9c17bd8d-6ff3-4ded-a55e-0220150b9066',
                'slug' => 'permissionrole.edit',
                'nama' => 'Menampilkan form edit Permissionrole',
                'action' => 'edit',
                'group' => 'permissionrole',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            53 =>
            array(
                'id' => '9c17bd8d-704f-438d-92ee-8446febd8063',
                'slug' => 'permissionrole.index',
                'nama' => 'Melihat daftar Permissionrole',
                'action' => 'index',
                'group' => 'permissionrole',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            54 =>
            array(
                'id' => '9c17bd8d-70ab-4810-8303-2f0c5b4e7dc2',
                'slug' => 'permissionrole.show',
                'nama' => 'Menampilkan detail Permissionrole',
                'action' => 'show',
                'group' => 'permissionrole',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            55 =>
            array(
                'id' => '9c17bd8d-710f-44f7-af69-c4adbe9559cc',
                'slug' => 'permissionrole.store',
                'nama' => 'Menyimpan form tambah Permissionrole',
                'action' => 'store',
                'group' => 'permissionrole',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            56 =>
            array(
                'id' => '9c17bd8d-7184-4add-bc53-9b39b04eb52c',
                'slug' => 'permissionrole.update',
                'nama' => 'Menyimpan form edit Permissionrole',
                'action' => 'update',
                'group' => 'permissionrole',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            57 =>
            array(
                'id' => '9c17bd8d-7600-40c2-b2d3-c4bd0a1031d3',
                'slug' => 'roleuser.create',
                'nama' => 'Menampilkan form tambah Roleuser',
                'action' => 'create',
                'group' => 'roleuser',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            58 =>
            array(
                'id' => '9c17bd8d-765e-4df8-a792-b0024dfef955',
                'slug' => 'roleuser.destroy',
                'nama' => 'Menghapus Roleuser',
                'action' => 'destroy',
                'group' => 'roleuser',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            59 =>
            array(
                'id' => '9c17bd8d-76a3-47fa-87f6-05630f2f8cb0',
                'slug' => 'roleuser.edit',
                'nama' => 'Menampilkan form edit Roleuser',
                'action' => 'edit',
                'group' => 'roleuser',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            60 =>
            array(
                'id' => '9c17bd8d-76eb-4d18-b0f8-d0e337f961d2',
                'slug' => 'roleuser.index',
                'nama' => 'Melihat daftar Roleuser',
                'action' => 'index',
                'group' => 'roleuser',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            61 =>
            array(
                'id' => '9c17bd8d-7748-4968-8e71-f502e510d34e',
                'slug' => 'roleuser.show',
                'nama' => 'Menampilkan detail Roleuser',
                'action' => 'show',
                'group' => 'roleuser',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            62 =>
            array(
                'id' => '9c17bd8d-7794-44e0-8bad-db390fb71ca6',
                'slug' => 'roleuser.store',
                'nama' => 'Menyimpan form tambah Roleuser',
                'action' => 'store',
                'group' => 'roleuser',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            63 =>
            array(
                'id' => '9c17bd8d-77dd-4a61-b170-2e1550b80456',
                'slug' => 'roleuser.update',
                'nama' => 'Menyimpan form edit Roleuser',
                'action' => 'update',
                'group' => 'roleuser',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            64 =>
            array(
                'id' => '9c17bd8d-781f-41a6-b767-ac5c8ba9979f',
                'slug' => 'scope.create',
                'nama' => 'Menampilkan form tambah Scope',
                'action' => 'create',
                'group' => 'scope',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            65 =>
            array(
                'id' => '9c17bd8d-7861-431e-ba77-cc93cefea6b9',
                'slug' => 'scope.destroy',
                'nama' => 'Menghapus Scope',
                'action' => 'destroy',
                'group' => 'scope',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            66 =>
            array(
                'id' => '9c17bd8d-78ac-43d7-bc59-265a74053e6d',
                'slug' => 'scope.edit',
                'nama' => 'Menampilkan form edit Scope',
                'action' => 'edit',
                'group' => 'scope',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            67 =>
            array(
                'id' => '9c17bd8d-78fa-4a35-b2f0-c7122ccee622',
                'slug' => 'scope.index',
                'nama' => 'Melihat daftar Scope',
                'action' => 'index',
                'group' => 'scope',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            68 =>
            array(
                'id' => '9c17bd8d-794b-45a4-9653-8d1e00c152b6',
                'slug' => 'scope.show',
                'nama' => 'Menampilkan detail Scope',
                'action' => 'show',
                'group' => 'scope',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            69 =>
            array(
                'id' => '9c17bd8d-7994-4785-9830-d5cd3c9dee77',
                'slug' => 'scope.store',
                'nama' => 'Menyimpan form tambah Scope',
                'action' => 'store',
                'group' => 'scope',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            70 =>
            array(
                'id' => '9c17bd8d-79d8-49b3-b288-3021c333a638',
                'slug' => 'scope.update',
                'nama' => 'Menyimpan form edit Scope',
                'action' => 'update',
                'group' => 'scope',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
        ));
    }
}