<?php

namespace Abianbiya\Laralag\Seeders;

use Illuminate\Database\Seeder;

class PermissionTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('permission')->delete();
        
        \DB::table('permission')->insert(array (
            0 => 
            array (
                'id' => '9c143c88-b996-4638-8a44-2696abccfd2a',
                'slug' => 'menu.create',
                'nama' => 'menu.create',
                'action' => 'create',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            1 => 
            array (
                'id' => '9c143c88-bc38-4705-93c2-e026392f96f9',
                'slug' => 'menu.destroy',
                'nama' => 'menu.destroy',
                'action' => 'destroy',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            2 => 
            array (
                'id' => '9c143c88-bca4-406a-a587-f08de3200a5f',
                'slug' => 'menu.edit',
                'nama' => 'menu.edit',
                'action' => 'edit',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            3 => 
            array (
                'id' => '9c143c88-bcfc-4513-b7bc-e0ee069131d7',
                'slug' => 'menu.index',
                'nama' => 'menu.index',
                'action' => 'index',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            4 => 
            array (
                'id' => '9c143c88-bd54-40e2-8b34-386e7f0e1aa4',
                'slug' => 'menu.show',
                'nama' => 'menu.show',
                'action' => 'show',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            5 => 
            array (
                'id' => '9c143c88-bdaf-4548-bf26-e64e152fcf20',
                'slug' => 'menu.store',
                'nama' => 'menu.store',
                'action' => 'store',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            6 => 
            array (
                'id' => '9c143c88-be19-44fd-a9c7-720abce3da06',
                'slug' => 'menu.update',
                'nama' => 'menu.update',
                'action' => 'update',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            7 => 
            array (
                'id' => '9c143c88-be66-44f1-993d-5e67a8b0b976',
                'slug' => 'menugroup.create',
                'nama' => 'menugroup.create',
                'action' => 'create',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            8 => 
            array (
                'id' => '9c143c88-bec4-4788-9a24-41d787f1cc45',
                'slug' => 'menugroup.destroy',
                'nama' => 'menugroup.destroy',
                'action' => 'destroy',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            9 => 
            array (
                'id' => '9c143c88-bf18-4d75-9618-5f124a6a5903',
                'slug' => 'menugroup.edit',
                'nama' => 'menugroup.edit',
                'action' => 'edit',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            10 => 
            array (
                'id' => '9c143c88-bf78-45d8-bdbc-9972f51cad3f',
                'slug' => 'menugroup.index',
                'nama' => 'menugroup.index',
                'action' => 'index',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            11 => 
            array (
                'id' => '9c143c88-bfd6-496b-b680-a61c0e068ad8',
                'slug' => 'menugroup.show',
                'nama' => 'menugroup.show',
                'action' => 'show',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            12 => 
            array (
                'id' => '9c143c88-c039-4338-90f8-99dbbf21d7b6',
                'slug' => 'menugroup.store',
                'nama' => 'menugroup.store',
                'action' => 'store',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            13 => 
            array (
                'id' => '9c143c88-c0b2-4478-94d7-310a808beea7',
                'slug' => 'menugroup.update',
                'nama' => 'menugroup.update',
                'action' => 'update',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            14 => 
            array (
                'id' => '9c143c88-c11d-4716-9268-2e05212e5199',
                'slug' => 'module.create',
                'nama' => 'module.create',
                'action' => 'create',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            15 => 
            array (
                'id' => '9c143c88-c180-45ef-a8d1-7de0d4c8eb46',
                'slug' => 'module.destroy',
                'nama' => 'module.destroy',
                'action' => 'destroy',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            16 => 
            array (
                'id' => '9c143c88-c1f5-44c5-baf4-c530701657b5',
                'slug' => 'module.edit',
                'nama' => 'module.edit',
                'action' => 'edit',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            17 => 
            array (
                'id' => '9c143c88-c2c5-4bc9-bd35-a7913968bd52',
                'slug' => 'module.index',
                'nama' => 'module.index',
                'action' => 'index',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            18 => 
            array (
                'id' => '9c143c88-c322-47d3-8b90-6ae20730aa02',
                'slug' => 'module.show',
                'nama' => 'module.show',
                'action' => 'show',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            19 => 
            array (
                'id' => '9c143c88-c388-4f20-9d74-a327cd2cbaf0',
                'slug' => 'module.store',
                'nama' => 'module.store',
                'action' => 'store',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            20 => 
            array (
                'id' => '9c143c88-c3fa-4fac-a19e-8e5fa1a92295',
                'slug' => 'module.update',
                'nama' => 'module.update',
                'action' => 'update',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            21 => 
            array (
                'id' => '9c143c88-c461-4192-8594-8f8761a0ac2b',
                'slug' => 'permission.create',
                'nama' => 'permission.create',
                'action' => 'create',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            22 => 
            array (
                'id' => '9c143c88-c4c2-4366-a231-887eb37d9f56',
                'slug' => 'permission.destroy',
                'nama' => 'permission.destroy',
                'action' => 'destroy',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            23 => 
            array (
                'id' => '9c143c88-c53c-4169-9006-3d8e24764851',
                'slug' => 'permission.edit',
                'nama' => 'permission.edit',
                'action' => 'edit',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            24 => 
            array (
                'id' => '9c143c88-c5a0-42a5-aa92-e75111720ffa',
                'slug' => 'permission.index',
                'nama' => 'permission.index',
                'action' => 'index',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            25 => 
            array (
                'id' => '9c143c88-c60a-4fcf-98cd-3030d67dd745',
                'slug' => 'permission.show',
                'nama' => 'permission.show',
                'action' => 'show',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            26 => 
            array (
                'id' => '9c143c88-c668-41ae-91fd-7836ce41e978',
                'slug' => 'permission.store',
                'nama' => 'permission.store',
                'action' => 'store',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            27 => 
            array (
                'id' => '9c143c88-c6cb-48e9-99ac-e8e44b2e0c04',
                'slug' => 'permission.update',
                'nama' => 'permission.update',
                'action' => 'update',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            28 => 
            array (
                'id' => '9c143c88-c735-4241-b049-c07d5c03cd30',
                'slug' => 'post.create',
                'nama' => 'post.create',
                'action' => 'create',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            29 => 
            array (
                'id' => '9c143c88-c798-40bd-8ab7-7b07444882f3',
                'slug' => 'post.destroy',
                'nama' => 'post.destroy',
                'action' => 'destroy',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            30 => 
            array (
                'id' => '9c143c88-c7f6-4b31-9c35-35561fc9ebae',
                'slug' => 'post.edit',
                'nama' => 'post.edit',
                'action' => 'edit',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            31 => 
            array (
                'id' => '9c143c88-c887-4ab5-92a2-dbfbffabbaf1',
                'slug' => 'post.index',
                'nama' => 'post.index',
                'action' => 'index',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            32 => 
            array (
                'id' => '9c143c88-c913-457c-aafe-0617067f7b7e',
                'slug' => 'post.show',
                'nama' => 'post.show',
                'action' => 'show',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            33 => 
            array (
                'id' => '9c143c88-c97a-4942-9317-78ff24955ade',
                'slug' => 'post.store',
                'nama' => 'post.store',
                'action' => 'store',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            34 => 
            array (
                'id' => '9c143c88-c9e1-4746-942d-ebfb87b28228',
                'slug' => 'post.update',
                'nama' => 'post.update',
                'action' => 'update',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            
            42 => 
            array (
                'id' => '9c143c88-cd0d-455f-a5f2-1bd044f5fe71',
                'slug' => 'role.create',
                'nama' => 'role.create',
                'action' => 'create',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            43 => 
            array (
                'id' => '9c143c88-cd60-44c7-a1f2-6b22b9dfbe60',
                'slug' => 'role.destroy',
                'nama' => 'role.destroy',
                'action' => 'destroy',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            44 => 
            array (
                'id' => '9c143c88-cdb0-43f0-b45e-a0075e011efe',
                'slug' => 'role.edit',
                'nama' => 'role.edit',
                'action' => 'edit',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            45 => 
            array (
                'id' => '9c143c88-ce0d-44c4-bf83-923a5e3ed3d8',
                'slug' => 'role.index',
                'nama' => 'role.index',
                'action' => 'index',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            46 => 
            array (
                'id' => '9c143c88-ce63-42f9-9e4d-b2412bacde79',
                'slug' => 'role.permission.update',
                'nama' => 'role.permission.update',
                'action' => 'update',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            47 => 
            array (
                'id' => '9c143c88-ceb7-437c-a417-f7506d1d92bf',
                'slug' => 'role.show',
                'nama' => 'role.show',
                'action' => 'show',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            48 => 
            array (
                'id' => '9c143c88-cef9-4582-96b3-f7affd56ec22',
                'slug' => 'role.store',
                'nama' => 'role.store',
                'action' => 'store',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            49 => 
            array (
                'id' => '9c143c88-cf3b-4bce-8c18-44df5b41e35a',
                'slug' => 'role.update',
                'nama' => 'role.update',
                'action' => 'update',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            57 => 
            array (
                'id' => '9c143c88-d157-4c5c-b2a4-12d6b674a6c2',
                'slug' => 'user.create',
                'nama' => 'user.create',
                'action' => 'create',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            58 => 
            array (
                'id' => '9c143c88-d1ac-4ec9-a099-108654b86be9',
                'slug' => 'user.destroy',
                'nama' => 'user.destroy',
                'action' => 'destroy',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            59 => 
            array (
                'id' => '9c143c88-d1fe-4c64-a45c-a0eefc3d65a3',
                'slug' => 'user.edit',
                'nama' => 'user.edit',
                'action' => 'edit',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            60 => 
            array (
                'id' => '9c143c88-d243-4623-bdf8-c81eba2eab32',
                'slug' => 'user.index',
                'nama' => 'user.index',
                'action' => 'index',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            61 => 
            array (
                'id' => '9c143c88-d280-4222-9f4b-b6760f2849e5',
                'slug' => 'user.show',
                'nama' => 'user.show',
                'action' => 'show',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            62 => 
            array (
                'id' => '9c143c88-d2bd-4ddd-825d-66ee681985b6',
                'slug' => 'user.store',
                'nama' => 'user.store',
                'action' => 'store',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            63 => 
            array (
                'id' => '9c143c88-d2f9-493b-a346-ce5d252032de',
                'slug' => 'user.update',
                'nama' => 'user.update',
                'action' => 'update',
                'group' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-19 08:36:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
        ));
        
        
    }
}